# Autogenerated wrapper script for WhereAmI_jll for aarch64-apple-darwin
export libwai

JLLWrappers.@generate_wrapper_header("WhereAmI")
JLLWrappers.@declare_library_product(libwai, "@rpath/libwai.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libwai,
        "lib/libwai.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
