# Autogenerated wrapper script for WhereAmI_jll for x86_64-w64-mingw32
export libwai

JLLWrappers.@generate_wrapper_header("WhereAmI")
JLLWrappers.@declare_library_product(libwai, "libwai.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libwai,
        "bin\\libwai.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
